[package]
name = "stress-rs"
version = "0.1.0"
authors = ["Kenny Kerr <kenny.kerr@microsoft.com>"]
edition = "2018"

[dependencies]
winrt = { path = "./winrt-rs" }
bindings = { path = "bindings" }

[package.metadata.winrt.dependencies]
"Microsoft.Windows.SDK.Contracts" = "10.0.19041.1"